# Generated by Django 3.2.8 on 2022-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210517_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
